/**
 * Words and phrases to avoid in AI-generated content.
 * These are commonly overused by LLMs and make content feel robotic.
 */

export const avoidPhrases = [
  'Indeed',
  'Furthermore',
  'However',
  'Notably',
  'Therefore',
  'Additionally',
  'Significantly',
  'Consequently',
  'Thus',
  'Moreover',
  'Subsequently',
  'Accordingly',
  'Based on',
  'It suggests that',
  'It is likely that',
  'In conclusion',
  'Overall',
  'This means that',
  'Given that',
  'Considering the context',
  'On the other hand',
  'This could indicate that',
  'To summarize',
  'According to the data',
  'From my understanding',
  'It is important to consider',
  'Taking into account',
  'One might conclude',
  'We can infer that',
  'From an ethical standpoint',
  'To clarify further',
  'The reasoning behind this is',
  'It could be argued that',
  'While it is true that',
  'This raises the question',
  'It appears that',
  'Further analysis shows',
  'Considering multiple perspectives',
  'It is evident that',
  'A possible interpretation is',
  'It is worth noting that',
];

export const excludeTerms = [
  'Delve',
  'In conclusion',
  'Rapid pace of development',
  'Only time will tell',
  'Bringing us one step closer',
  'Push the boundaries',
  'Paving the way',
  'Revolutionize the way',
  'Transformative power',
  'Groundbreaking advancement',
  'Ethical',
  'Perspective',
  'Clarify',
  'Infer',
  'Reasoning',
  'Contextualize',
  'Evidence',
  'Approach',
  'Insight',
  'Meld',
];

export const removePhrases = [
  "In today's digital age",
  'Designed to enhance',
  'It is advisable',
  'When it comes to',
  'In the realm of',
  'Game changer',
  'Unlock the secrets',
  'Unveil the secrets',
  'Robust',
  'Cutting-edge',
  'Rapidly expanding',
  'Mastering',
  'Harness',
  'Imagine',
  "It's important to note",
  'Delve into',
  'Tapestry',
  'Bustling',
  'In summary',
  'Remember that',
  'Take a dive into',
  'Navigating',
  'Landscape',
  'Testament',
  'In the world of',
  'Realm',
  'Embark',
  'Analogies to being a conductor or to music',
  'Vibrant',
  'Metropolis',
  'Firstly',
  'Moreover',
  'Crucial',
  'To consider',
  'Essential',
  'There are a few considerations',
  'Ensure',
  "It's essential to",
  'Furthermore',
  'Vital',
  'Keen',
  'Fancy',
  'As a professional',
  'However',
  'Therefore',
  'Additionally',
  'Specifically',
  'Generally',
  'Consequently',
  'Importantly',
  'Indeed',
  'Thus',
  'Alternatively',
  'Notably',
  'As well as',
  'Despite',
  'Essentially',
  'While',
  'Unless',
  'Also',
  'Even though',
  'Because',
  'In contrast',
  'Although',
  'In order to',
  'Due to',
  'Even if',
  'Given that',
  'Arguably',
  'You may want to',
  'On the other hand',
  'As previously mentioned',
  "It's worth noting that",
  'To summarize',
  'Ultimately',
  'To put it simply',
  'Promptly',
];

/**
 * Generate the banned words section for the prompt
 */
export function generateBannedWordsSection(): string {
  return `- Avoid the following common phrases and words:

${avoidPhrases.join(', ')}.

- Completely Exclude these specific overused terms:

${excludeTerms.join(', ')}.

- Remove these phrases that often appear clichéd or generic:

${removePhrases.join(', ')}.`;
}
